from app.prompts.resume_prompts import RESUME_PARSER_SYSTEM_PROMPT, RESUME_PARSER_USER_PROMPT
from app.prompts.question_prompts import QUESTION_GENERATOR_SYSTEM_PROMPT, QUESTION_GENERATOR_USER_PROMPT
from app.prompts.evaluation_prompts import ANSWER_EVALUATION_SYSTEM_PROMPT, ANSWER_EVALUATION_USER_PROMPT
from app.prompts.report_prompts import FINAL_REPORT_SYSTEM_PROMPT, FINAL_REPORT_USER_PROMPT

__all__ = [
    "RESUME_PARSER_SYSTEM_PROMPT",
    "RESUME_PARSER_USER_PROMPT",
    "QUESTION_GENERATOR_SYSTEM_PROMPT",
    "QUESTION_GENERATOR_USER_PROMPT",
    "ANSWER_EVALUATION_SYSTEM_PROMPT",
    "ANSWER_EVALUATION_USER_PROMPT",
    "FINAL_REPORT_SYSTEM_PROMPT",
    "FINAL_REPORT_USER_PROMPT",
]

